# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

before_script:
 - npm install --silent

stages:
 - test
 - build

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/
  
run_tests:
 stage: test
 script:
  - npm test
      
build_project:
 stage: build
 script:
  - npm run build --report
 