export const TAKE_SNACK = 'TAKE_SNACK'

export const INCREASE_SNACK = 'INCREASE_SNACK'

export const DECREASE_SNACK = 'DECREASE_SNACK'

export const ADD_SNACKTYPE = 'ADD_SNACKTYPE'

export const DELETE_SNACKTYPE = 'DELETE_SNACKTYPE'

export const ADD_COMPENSATION = 'ADD_COMPENSATION'

export const REMOVE_COMPENSATION = 'REMOVE_COMPENSATION'
